"""
Builds target/gh-pages-publish/index.html: one bookmarkable landing page
linking to the Allure report, every Extent report file present this run,
coverage, Test Impact Analysis, the self-healing summary, the flaky-test
trend, and a trend-over-time table for all four — so viewing any of this
only ever requires the Pages URL, never downloading the workflow's
artifact zip or clicking between separate report pages to piece together
overall test health.

Rewritten in Python (was inline bash/printf) once it needed to render
tables from JSON rather than just a flat link list — HTML-from-JSON is a
lot less error-prone here than continuing to hand-quote it through shell.
"""
import html
import json
import os
from datetime import datetime, timezone

PUBLISH_DIR = "target/gh-pages-publish"
ALLURE_INDEX = os.path.join(PUBLISH_DIR, "allure-report", "index.html")
EXTENT_DIR = os.path.join(PUBLISH_DIR, "extent-report")
SEGMENTED_DIR = os.path.join(PUBLISH_DIR, "allure-segmented")
SEGMENTS_MANIFEST = os.path.join(SEGMENTED_DIR, "segments.json")
SELF_HEALING_SUMMARY_PATH = "target/self-healing-summary.json"
FLAKY_TESTS_PATH = "target/flaky-tests.json"
COVERAGE_SUMMARY_PATH = "target/coverage-summary.json"
TIA_SUMMARY_PATH = "target/tia/impact-summary.json"
DASHBOARD_HISTORY_PATH = os.path.join(PUBLISH_DIR, "history", "dashboard-history.json")
OUTPUT_PATH = os.path.join(PUBLISH_DIR, "index.html")

STYLE = """
body { font-family: -apple-system, Segoe UI, Roboto, Arial, sans-serif; margin: 2rem auto; max-width: 760px; line-height: 1.6; padding: 0 1rem; }
h1 { font-size: 1.4rem; }
h2 { font-size: 1.05rem; margin-top: 2rem; border-bottom: 1px solid #ddd; padding-bottom: 0.3rem; }
ul { padding-left: 1.2rem; }
table { border-collapse: collapse; width: 100%; margin-top: 0.5rem; font-size: 0.9rem; }
th, td { text-align: left; padding: 0.35rem 0.6rem; border-bottom: 1px solid #eee; }
th { color: #555; font-weight: 600; }
small { color: #666; }
.muted { color: #888; font-style: italic; }
.badge { display: inline-block; padding: 0.1rem 0.5rem; border-radius: 999px; font-size: 0.8rem; }
.badge-pass { background: #e6f4ea; color: #1e7e34; }
.badge-fail { background: #fdecea; color: #c0392b; }
.badge-skip { background: #f1f1f1; color: #666; }
"""


def load_json(path):
    if not os.path.exists(path):
        return None
    try:
        with open(path, encoding="utf-8") as f:
            return json.load(f)
    except (json.JSONDecodeError, OSError):
        return None


def render_allure_section():
    if not os.path.exists(ALLURE_INDEX):
        return '<p class="muted">No Allure report found for this run.</p>'
    combined = '<li><a href="allure-report/index.html"><strong>All Results (Combined)</strong></a></li>'
    return f"<ul>{combined}{render_segmented_section()}</ul>"


def render_segmented_section():
    """Renders the browser-wise/site-wise/test-type-wise/category-wise Allure
    reports generated by Scripts/generate_segmented_reports.py, grouped under
    the same dimension headings the script itself uses, so it's obvious which
    report is which instead of one undifferentiated combined dashboard."""
    manifest = load_json(SEGMENTS_MANIFEST)
    if not manifest:
        return ""
    by_dimension = {}
    for seg in manifest:
        if not seg.get("generated"):
            continue
        by_dimension.setdefault(seg["dimensionLabel"], []).append(seg)

    items = ""
    for dimension_label in ("By Browser", "By Site / App", "By Test Type", "By Category",
                            "By Severity", "Flaky (passed only after a retry)"):
        segs = sorted(by_dimension.get(dimension_label, []), key=lambda s: s["value"])
        if not segs:
            continue
        links = "".join(
            f'<li><a href="allure-segmented/{html.escape(seg["dimension"])}/{html.escape(seg["slug"])}'
            f'/report/index.html">{html.escape(str(seg["value"]))}</a> '
            f'<small>({seg["count"]} test{"s" if seg["count"] != 1 else ""})</small></li>'
            for seg in segs
        )
        items += f"<li>{html.escape(dimension_label)}<ul>{links}</ul></li>"
    return items


def render_extent_section():
    if not os.path.isdir(EXTENT_DIR):
        return '<p class="muted">No Extent report found for this run.</p>'
    # Recursive: ExtentManager nests reports as <site>/<browser-or-mobile>/<suite>/
    # index.html so each site/browser/test-type combination gets its own physical
    # report file. A flat, non-recursive glob here used to silently find none of
    # them once that nesting was introduced — this walks the whole tree instead
    # and labels each link with the path segments that make it unique.
    files = sorted(
        os.path.relpath(os.path.join(dirpath, fname), EXTENT_DIR)
        for dirpath, _dirs, filenames in os.walk(EXTENT_DIR)
        for fname in filenames
        if fname == "index.html"
    )
    if not files:
        return '<p class="muted">No Extent report found for this run.</p>'
    items = "".join(
        f'<li><a href="extent-report/{html.escape(rel.replace(os.sep, "/"))}">'
        f'{html.escape(rel.replace(os.sep, "/").rsplit("/index.html", 1)[0])}</a></li>'
        for rel in files
    )
    return f"<ul>{items}</ul>"


def render_self_healing_section():
    summary = load_json(SELF_HEALING_SUMMARY_PATH)
    if not summary or not summary.get("total"):
        return '<p class="muted">No locators needed self-healing this run.</p>'
    rows = []
    for event in summary["events"][:25]:
        # Score formatting pulled out to its own line (rather than nested
        # in the f-string below) since pre-3.12 Python disallows a
        # backslash-containing expression — which html.escape's quoting
        # would otherwise require — inside an f-string's {} braces.
        score_text = html.escape(f"{float(event.get('score', 0) or 0):.2f}")
        rows.append(
            "<tr>"
            f"<td>{html.escape(str(event.get('site', '')))}</td>"
            f"<td>{html.escape(str(event.get('elementKey', '')))}</td>"
            f"<td>{html.escape(str(event.get('originalLocator', '')))}</td>"
            f"<td>{html.escape(str(event.get('healedDescription', '')))}</td>"
            f"<td>{score_text}</td>"
            "</tr>"
        )
    more = ""
    if summary["total"] > 25:
        more = f'<p class="muted">...and {summary["total"] - 25} more. See self-healing-report.json.</p>'
    table = (
        "<table><thead><tr><th>Site</th><th>Element</th><th>Original Locator</th>"
        f"<th>Healed As</th><th>Score</th></tr></thead><tbody>{''.join(rows)}</tbody></table>"
    )
    by_site = ", ".join(f"{site}: {count}" for site, count in summary.get("bySite", {}).items())
    return f"<p><strong>{summary['total']}</strong> locator(s) drifted and were auto-healed this run ({by_site}).</p>{table}{more}"


def render_flaky_section():
    report = load_json(FLAKY_TESTS_PATH)
    if not report or not report.get("flaky_count"):
        window = report.get("window_runs") if report else None
        note = f" (last {window} runs)" if window else ""
        return f'<p class="muted">No flaky tests detected{note}.</p>'
    rows = []
    for entry in report["flaky"][:25]:
        statuses = " ".join(
            f'<span class="badge badge-{s}">{s}</span>' for s in entry["recent_statuses"]
        )
        rows.append(
            "<tr>"
            f"<td>{html.escape(entry['test'])}</td>"
            f"<td>{entry['pass_count']}</td>"
            f"<td>{entry['fail_count']}</td>"
            f"<td>{statuses}</td>"
            "</tr>"
        )
    table = (
        "<table><thead><tr><th>Test</th><th>Passes</th><th>Fails</th>"
        f"<th>Recent (oldest &rarr; newest)</th></tr></thead><tbody>{''.join(rows)}</tbody></table>"
    )
    return (
        f"<p><strong>{report['flaky_count']}</strong> test(s) flip-flopped between pass and fail "
        f"over the last {report['window_runs']} run(s).</p>{table}"
    )


def render_coverage_section():
    summary = load_json(COVERAGE_SUMMARY_PATH)
    if not summary:
        return '<p class="muted">No coverage data for this run (coverage-gate job may have had no .exec data to merge, or hasn\'t run yet).</p>'
    status_class = "badge-pass" if summary["passed"] else "badge-fail"
    status_text = "PASS" if summary["passed"] else "FAIL"
    return (
        f'<p><strong>{summary["line_pct"]}%</strong> line coverage on '
        f'<code>{html.escape(summary["scope"])}</code> '
        f'({summary["line_covered"]}/{summary["line_total"]} lines) '
        f'<span class="badge {status_class}">{status_text}</span> '
        f'against the {summary["threshold_pct"]}% gate. '
        f'<small>See the <code>jacoco-merged-report</code> artifact for the full drill-down.</small></p>'
    )


def render_tia_section():
    summary = load_json(TIA_SUMMARY_PATH)
    if not summary:
        return '<p class="muted">No Test Impact Analysis data for this run — TIA only runs on pull requests.</p>'
    if summary.get("mode") == "FULL":
        return (
            '<p><strong>FULL</strong> mode — TIA fell back to running every test class this run '
            '(see the <code>test-impact-analysis</code> artifact\'s <code>impact-report.md</code> for why).</p>'
        )
    impacted = summary.get("impacted_count", 0)
    total = summary.get("total_test_classes", 0)
    pct = round(100.0 * impacted / total, 1) if total else 0.0
    return (
        f'<p><strong>{impacted} / {total}</strong> test classes selected ({pct}%) across '
        f'<strong>{summary.get("changed_files_count", 0)}</strong> changed file(s). '
        f'<small>See the <code>test-impact-analysis</code> artifact\'s <code>impact-report.md</code> for the full breakdown.</small></p>'
    )


def render_trends_section():
    """Renders the last N runs of coverage %, self-healing count, flaky
    count, and TIA-impacted % as a compact table — the one thing the
    per-section snapshots above can't show: whether any of these is
    trending the wrong way over time, not just what it is right now."""
    history = load_json(DASHBOARD_HISTORY_PATH)
    if not history:
        return '<p class="muted">No history yet — this trend builds up across future runs.</p>'
    rows = []
    for entry in reversed(history[-15:]):
        ts = entry.get("timestamp", "")[:10]  # date only, keeps the table narrow
        coverage = f'{entry["coverage_pct"]}%' if entry.get("coverage_pct") is not None else "&mdash;"
        tia = f'{entry["tia_impacted_pct"]}%' if entry.get("tia_impacted_pct") is not None else "&mdash;"
        rows.append(
            "<tr>"
            f"<td>{html.escape(ts)}</td>"
            f"<td>{html.escape(str(entry.get('event', '')))}</td>"
            f"<td>{coverage}</td>"
            f"<td>{entry.get('self_healing_count', 0)}</td>"
            f"<td>{entry.get('flaky_count', 0)}</td>"
            f"<td>{tia}</td>"
            "</tr>"
        )
    return (
        "<table><thead><tr><th>Date</th><th>Trigger</th><th>Coverage</th>"
        "<th>Self-Healed</th><th>Flaky</th><th>TIA Selected</th></tr></thead>"
        f"<tbody>{''.join(rows)}</tbody></table>"
        f'<p><small>Last {len(history)} run(s) retained. TIA columns show &mdash; on non-PR runs (expected — TIA only runs on pull requests).</small></p>'
    )


def main():
    os.makedirs(PUBLISH_DIR, exist_ok=True)
    generated_at = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M:%S UTC")
    run_id = os.environ.get("GITHUB_RUN_ID", "unknown")

    page = f"""<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Selenium Automation Framework - Test Reports</title>
  <style>{STYLE}</style>
</head>
<body>
  <h1>Selenium Automation Framework - Test Reports</h1>
  <p><small>Last updated: {generated_at} &middot; Run: {run_id}</small></p>

  <h2>Allure</h2>
  {render_allure_section()}

  <h2>Extent</h2>
  {render_extent_section()}

  <h2>Coverage (core/)</h2>
  {render_coverage_section()}

  <h2>Test Impact Analysis</h2>
  {render_tia_section()}

  <h2>Self-Healing Locators</h2>
  {render_self_healing_section()}

  <h2>Flaky Test Trend</h2>
  {render_flaky_section()}

  <h2>Trends Over Time</h2>
  {render_trends_section()}
</body>
</html>
"""
    with open(OUTPUT_PATH, "w", encoding="utf-8") as f:
        f.write(page)
    print(f"Wrote {OUTPUT_PATH}")


if __name__ == "__main__":
    main()
