package com.automation.core.ai;

/**
 * The model's opinion on why one test failed — see {@link AiExceptionAnalyzer}.
 * Purely a report-time artifact: nothing in the framework acts on this
 * automatically (no auto-retry, no auto-edited source); it exists to be
 * read by a human triaging the failure.
 */
public final class AiFailureAnalysis {

    public final String rootCause;
    public final String explanation;
    public final String suggestedFix;

    public AiFailureAnalysis(String rootCause, String explanation, String suggestedFix) {
        this.rootCause = rootCause;
        this.explanation = explanation;
        this.suggestedFix = suggestedFix;
    }

    /** Plain-text rendering used for the Allure/ReportPortal attachment. */
    public String toReportText() {
        StringBuilder sb = new StringBuilder();
        sb.append("Root cause: ").append(orUnspecified(rootCause)).append(System.lineSeparator())
            .append(System.lineSeparator());
        sb.append("Explanation:").append(System.lineSeparator())
            .append(orUnspecified(explanation)).append(System.lineSeparator())
            .append(System.lineSeparator());
        sb.append("Suggested fix:").append(System.lineSeparator())
            .append(orUnspecified(suggestedFix)).append(System.lineSeparator())
            .append(System.lineSeparator());
        sb.append("(Generated by a local/remote LLM from the failure evidence above — verify before acting on it.)");
        return sb.toString();
    }

    private static String orUnspecified(String s) {
        return s == null || s.isBlank() ? "(unspecified)" : s;
    }
}
